# Generated by Django 4.0.6 on 2022-08-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='school',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
