# Generated by Django 4.0.6 on 2022-08-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.IntegerField()),
                ('dispute_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DebtorsPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('global_student_id', models.CharField(max_length=120)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('debt_status', models.CharField(max_length=120)),
                ('debt_type', models.CharField(max_length=120)),
                ('debt_creation_date', models.DateField(auto_now_add=True)),
                ('debt_payment_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_id', models.IntegerField()),
                ('dispute_description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('student_government_id', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
            ],
        ),
    ]
