# Generated by Django 4.0.6 on 2022-08-11 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorsPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_government_id', models.CharField(default=None, max_length=120)),
                ('government_id', models.CharField(default=None, max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('school_name', models.CharField(max_length=120, null=True)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('debt_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('debt_type', models.CharField(max_length=120)),
                ('debt_creation_date', models.DateField(auto_now_add=True)),
                ('debt_payment_date', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Debtor',
                'verbose_name_plural': 'Debtors',
                'ordering': ['-debt_creation_date'],
            },
        ),
        migrations.CreateModel(
            name='GlobalStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_government_id', models.CharField(blank=True, max_length=120, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_content', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('debtor_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='my_debtors.dispute')),
            ],
        ),
    ]
