# Generated by Django 4.0.6 on 2022-08-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_debtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtorsposting',
            old_name='first_name',
            new_name='student_first_name',
        ),
        migrations.RenameField(
            model_name='debtorsposting',
            old_name='last_name',
            new_name='student_last_name',
        ),
    ]
