# Generated by Django 4.0.6 on 2022-08-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_debtors', '0002_rename_first_name_debtorsposting_student_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtorsposting',
            name='student_first_name',
        ),
        migrations.RemoveField(
            model_name='debtorsposting',
            name='student_last_name',
        ),
        migrations.AddField(
            model_name='debtorsposting',
            name='student_full_name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
